image: node:9.11.1

pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install -g npm@latest
          - npm ci
          - npm test
          - npm run build:dev